<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Find restuarant near your location.')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('template/vendor/bootstrap/css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('template/vendor/fontawesome-free/css/all.min.css'))
            ->prependStylesheet($this->basePath('template/vendor/simple-line-icons/css/simple-line-icons.css'))
            ->prependStylesheet("https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic")
            ->prependStylesheet($this->basePath('template/css/landing-page.min.css'))
        ?>

    </head>

    <pulse-loader :loading="loading" :color="color" :size="size"></pulse-loader>
    <?= $this->content ?>
    <?= $this->inlineScript() ?>


    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('template/vendor/jquery/jquery.min.js'))
        ->prependFile($this->basePath('template/vendor/bootstrap/js/bootstrap.bundle.min.js'))
        ->prependFile($this->basePath('js/application.js'))
        ->prependFile('https://cdn.jsdelivr.net/npm/vue/dist/vue.js')
        ->prependFile('https://unpkg.com/axios/dist/axios.min.js')
    ?>
</html>
