<body>


  <!-- Masthead -->
  <header class="masthead text-white text-center">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">

        <div class="col-xl-9 mx-auto">
          <h1 class="mb-5">Restaurant near you.</h1>
        </div>

        <!-- Search form -->
        <div class="col-md-10 col-lg-8 col-xl-7 mx-auto" id="searchForm">
            <div class="form-row">
              <div class="col-12 col-md-9 mb-2 mb-md-0">
                <input type="text" class="form-control form-control-lg" placeholder="Enter you location" v-model="location" v-on:keyup.enter="startSearchRestaurants">
              </div>
              <div class="col-12 col-md-3">
                <button type="button" class="btn btn-block btn-lg btn-primary" v-on:click="startSearchRestaurants">Search</button>
              </div>
            </div>
        </div>

      </div>
    </div>
  </header>

  <!-- Search result section -->
  <section class="showcase">
    <div class="container-fluid">
        <div id="search-result-list">
            
            <!-- compoenent of restaurant list -->
            <restaurant-item v-for="item in restaurantList"v-bind:item="item"></restaurant-item>
        </div>

        <!-- Not found restaurants message. -->
        <div class="card mb-4 mt-4" v-show="isShowing" style="width: 100%;" id="not-found-message">
            <div class="card-body">
                <h1 class="text-center"> No restaurants found in this area. </h1>
            </div>
        </div>
  </section>

  <!-- Footer -->
  <footer class="footer bg-light">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
          <ul class="list-inline mb-2">
            <li class="list-inline-item">
              <a href="#">About</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Contact</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Terms of Use</a>
            </li>
            <li class="list-inline-item">&sdot;</li>
            <li class="list-inline-item">
              <a href="#">Privacy Policy</a>
            </li>
          </ul>
          <p class="text-muted small mb-4 mb-lg-0">&copy; Find me 2019. All Rights Reserved.</p>
        </div>
        <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
          <ul class="list-inline mb-0">
            <li class="list-inline-item mr-3">
              <a href="#">
                <i class="fab fa-facebook fa-2x fa-fw"></i>
              </a>
            </li>
            <li class="list-inline-item mr-3">
              <a href="#">
                <i class="fab fa-twitter-square fa-2x fa-fw"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-instagram fa-2x fa-fw"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

  
  <!-- template of component restaurants item -->
  <script type="text/x-template" id="restaurant-item">
        <div class="card mb-4 mt-4" style="width: 100%;">
            <div class="card-body">
                <h5 class="card-title">{{ item.name }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">Rating {{ item.rating }} </h6>
                <p class="card-text">{{ item.formatted_address }}</p>
            </div>
        </div>
  </script>